name: ecommerce

services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      DB_PASSWORD_FILE: /run/secrets/DATABASE_PASS
    secrets:
      - DATABASE_PASS
    depends_on:
      - backend

  backend:
    image: postgres:17
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD_FILE: /run/secrets/DATABASE_PASS
    secrets:
      - DATABASE_PASS
 
secrets:
  DATABASE_PASS:
    file: database.pass
